{
 "title": "vSphere Dashboards",
 "description": "A vSphere dashboard based on Prometheus and Telegraf(vSphere input+Prometheu output).",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "Telegraf" },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\"}, vcenter)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\"}, dcname)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values(vsphere_host_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\"}, dsname)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\"}, clustername)"
    }
   },
   {
    "name": "esxi",
    "label": "ESXi",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\"}, esxhostname)"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(vsphere_host_disk_read_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, disk)"
    }
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": {
     "query": "label_values(vsphere_host_net_bytesTx_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, interface)"
    }
   },
   {
    "name": "hba",
    "label": "HBA",
    "query": {
     "query": "label_values(vsphere_host_storageAdapter_read_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, adapter)"
    }
   },
   {
    "name": "vm",
    "label": "VM",
    "query": {
     "query": "label_values(vsphere_vm_cpu_usagemhz_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\"}, vmname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( group by (vcenter) (vsphere_host_cpu_usage_average))",
     "legendFormat": "vCenter Summary"
    },
    {
     "expr": "count(group by (clustername) (vsphere_host_cpu_usage_average))",
     "legendFormat": "Cluster Summary"
    },
    {
     "expr": "count(group by (esxhostname) (vsphere_host_cpu_usage_average))",
     "legendFormat": "ESXi Summary"
    },
    {
     "expr": "count(group by (vmname) (vsphere_vm_cpu_usage_average))",
     "legendFormat": "VM Summary"
    },
    {
     "expr": "count(group by (source) (vsphere_datastore_datastore_numberReadAveraged_average))",
     "legendFormat": "Datastore Summary"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_host_sys_uptime_latest{job=\"$job\",vcenter=\"$vcenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\"}",
     "legendFormat": "{{esxhostname}} "
    }
   ]
  },
  {
   "title": "CPU Avg Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",cpu=\"instance-total\"}",
     "legendFormat": "{{ esxhostname }}"
    }
   ]
  },
  {
   "title": "CPU Maximum Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_cpu_usage_maximum{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",cpu=\"instance-total\"}",
     "legendFormat": "{{ esxhostname }}"
    }
   ]
  },
  {
   "title": "CPU Wait",
   "type": "graph",
   "description": "Total CPU time spent in wait state.The wait total includes time spent the CPU Idle, CPU Swap Wait, and CPU I/O Wait states.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_cpu_wait_summation{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\"} / 200",
     "legendFormat": "{{ esxhostname }}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Avg Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_mem_usage_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\"}",
     "legendFormat": "{{ esxhostname }}"
    }
   ]
  },
  {
   "title": "Memory Maximum Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_mem_usage_maximum{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\"}",
     "legendFormat": "{{ esxhostname }}"
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_net_bytesRx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"}",
     "legendFormat": "{{ esxhostname }}/{{  interface }} Rx"
    },
    {
     "expr": "vsphere_host_net_bytesTx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"}",
     "legendFormat": "{{ esxhostname }}/{{  interface }} Tx"
    }
   ]
  },
  {
   "title": "Network Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_net_droppedRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
     "legendFormat": "{{ esxhostname }}/{{  interface }} Rx"
    },
    {
     "expr": "vsphere_host_net_droppedTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
     "legendFormat": "{{ esxhostname }}/{{  interface }} Tx"
    }
   ]
  },
  {
   "title": "Network Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_net_errorsRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
     "legendFormat": "{{ esxhostname }}/{{  interface }}  Rx"
    },
    {
     "expr": "vsphere_host_net_errorsTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",interface=~\"$nic\"} / 200",
     "legendFormat": "{{ esxhostname }}/{{  interface }} Tx"
    }
   ]
  },
  {
   "title": "Datastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datastore Throughput(Host View)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum by(dsname) (vsphere_host_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} R"
    },
    {
     "expr": "sum by(dsname) (vsphere_host_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} W"
    }
   ]
  },
  {
   "title": "Datastore IOPS(Host View)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by(dsname) (vsphere_host_datastore_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} R"
    },
    {
     "expr": "sum by(dsname) (vsphere_host_datastore_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} W"
    }
   ]
  },
  {
   "title": "Datastore Max Latency(Host View)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "max by(dsname) (vsphere_host_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} R"
    },
    {
     "expr": "max by(dsname) (vsphere_host_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} W"
    }
   ]
  },
  {
   "title": "Datastore Throughput(VM View)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum by(dsname) (vsphere_vm_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} R"
    },
    {
     "expr": "sum by(dsname) (vsphere_vm_datastore_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} W"
    }
   ]
  },
  {
   "title": "Datastore IOPS(VM View)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by(dsname) (vsphere_vm_datastore_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} R"
    },
    {
     "expr": "sum by(dsname) (vsphere_vm_datastore_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} W"
    }
   ]
  },
  {
   "title": "Datastore Max Latency(VM View)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "max by(dsname) (vsphere_vm_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} R"
    },
    {
     "expr": "max by(dsname) (vsphere_vm_datastore_totalReadLatency_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",dsname=~\"$datastore\"})",
     "legendFormat": "{{ dsname }} W"
    }
   ]
  },
  {
   "title": "VM CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_cpu_usage_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
     "legendFormat": "{{ esxhostname }}/{{ vmname }}"
    }
   ]
  },
  {
   "title": "CPU Latency",
   "type": "graph",
   "description": "Percent of time the virtual machine is unable to run because it is contending for access to the physical CPU(s)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_cpu_latency_average{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
     "legendFormat": "{{ esxhostname }}/{{ vmname }}"
    }
   ]
  },
  {
   "title": "CPU Wait",
   "type": "graph",
   "description": "Total CPU time spent in wait state.The wait total includes time spent the CPU Idle, CPU Swap Wait, and CPU I/O Wait states.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_cpu_wait_summation{job=\"$job\",vcenter=\"$vcenter\", dcname=\"$datacenter\", clustername=\"$cluster\",cpu=\"instance-total\",esxhostname=~\"$esxi\",vmname=~\"$vm\"} / 200",
     "legendFormat": "{{ esxhostname }}/{{ vmname }}"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Avg Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_mem_usage_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
     "legendFormat": "{{ esxhostname }}/{{ vmname }}"
    }
   ]
  },
  {
   "title": "Memory Swap In/Out Rate",
   "type": "graph",
   "description": "https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/memory_counters.html",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_mem_swapinRate_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
     "legendFormat": "{{ esxhostname }}/{{ vmname}} In"
    },
    {
     "expr": "vsphere_vm_mem_swapoutRate_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"}",
     "legendFormat": "{{ esxhostname }}/{{ vmname }} Out"
    }
   ]
  },
  {
   "title": "VM Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_net_bytesRx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"}",
     "legendFormat": "{{ esxhostname }}/{{ vmname }} Rx"
    },
    {
     "expr": "vsphere_vm_net_bytesTx_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"}",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} Tx"
    }
   ]
  },
  {
   "title": "Network Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_net_droppedRx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"} / 200",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} Rx"
    },
    {
     "expr": "vsphere_vm_net_droppedTx_summation{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",interface=\"instance-total\"} / 200",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} Tx"
    }
   ]
  },
  {
   "title": "VM Virtual Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vsphere_vm_virtualDisk_read_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",disk=\"instance-total\"}",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} R"
    },
    {
     "expr": "vsphere_vm_virtualDisk_write_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\",disk=\"instance-total\"}",
     "legendFormat": "{{ esxhostname }}/{{ vmname }} W"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum without(disk) (vsphere_vm_virtualDisk_numberReadAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} R"
    },
    {
     "expr": "sum without(disk) (vsphere_vm_virtualDisk_numberWriteAveraged_average{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} W"
    }
   ]
  },
  {
   "title": "Disk Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum without(disk) (vsphere_vm_virtualDisk_readOIO_latest{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} R"
    },
    {
     "expr": "sum without(disk) (vsphere_vm_virtualDisk_writeOIO_latest{job=\"$job\",vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
     "legendFormat": "{{ esxhostname }}/{{  vmname }} W"
    }
   ]
  },
  {
   "title": "Disk Max Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max without(disk) (vsphere_vm_virtualDisk_totalReadLatency_average{vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
     "legendFormat": "{{ esxhostname }}/{{ vmname }} R"
    },
    {
     "expr": "max without(disk) (vsphere_vm_virtualDisk_totalWriteLatency_average{vcenter=\"$vcenter\",dcname=\"$datacenter\",clustername=\"$cluster\",esxhostname=~\"$esxi\",vmname=~\"$vm\"})",
     "legendFormat": "{{ esxhostname }}/{{ vmname }} W"
    }
   ]
  }
 ]
}